my_bigquery_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_DATASET_ID') }}"
      keyfile: /opt/airflow/credentials/key.json
      location: us-central1
