version: 2

sources:
  - name: my_source
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('GCP_DATASET_ID') }}"
    tables:
      - name: transformed_data
        identifier: transformed_data
