FROM apache/airflow:2.5.1

USER root
COPY requirements.txt /tmp/requirements.txt

RUN apt-get update && apt-get install -y \
    openjdk-11-jdk \
    procps \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*


USER airflow

RUN pip install --user --no-cache-dir -r /tmp/requirements.txt

CMD ["airflow", "version"]
