FROM bitnami/spark:3.3.1
USER root
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN curl -L "..." -o /opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar

# Copy the script
COPY src/transform_data.py /opt/airflow/src/transform_data.py
# Make sure the directory exists, or create it:
RUN mkdir -p /opt/airflow/src

USER 1001


